language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python test.py 
deploy:
provider: elasticbeanstalk
access_key_id: 
  secure: "Encrypted <access-key-id>="
secret_access_key:
  secure: "Encypted <secret-access-key>="
region: "us-east-1"  
app: "example-app-name"
env: "example-app-environment"
bucket_name: "the-target-S3-bucket"